#!/bin/bash
tool1=`which rtf2html`
if [ -z "$tool1" ]; then echo "This tool $0 requires rtf2html"; exit 1; fi

tool2=`which html-text`
if [ -z "$tool2" ]; then echo "This tool $0 requires html-text"; exit 1; fi

infile="$1"
if [ -z "$infile" ]; then echo "Please specify input file"; exit 1; fi

TMPFILE=`mktemp`

# NTS: pdftotext will by default convert the PDF to text and write it to PDF.txt.
#      This tool needs pdftotext to convert to stdout instead, which is why the second argv is -
doit() {
    "$tool1" "$infile" >"$TMPFILE" || exit 1
    "$tool2" "$TMPFILE" | text-dictionary - || exit 1
}

doit; X=$?
rm -f "$TMPFILE"
exit $X

