#!/usr/bin/perl

use strict;

my $file = undef;

for (my $i=0;$i < @ARGV;) {
    my $a = $ARGV[$i++];

    if ($a =~ s/^-+//) {
        if ($a eq "file") {
            $file = $ARGV[$i++];
        }
        else {
            die "Unknown switch $a";
        }
    }
    else {
        die "Unexpected arg";
    }
}

die "--file spec required" unless defined($file);
die "$file does not exist" unless ( -f $file || -d $file );

my $mime_type = undef;
my $mime_encoding = undef;

# cover for cases the file tool cannot cover
open(T,"<",$file) || die "Cannot open file";
binmode(T);
my $bin;
read(T,$bin,4096);
# RIFF:WEBP for WebP files
if (substr($bin,0,4) eq "RIFF" && substr($bin,8,4) eq "WEBP") {
    $mime_type = "image/webp";
}
# done
close(T);

if (!defined($mime_type)) {
    # use file tool
    open(T,"-|","file","--brief","--mime","--",$file) || die "Cannot run file util";
    my $raw = <T>; chomp $raw;
    close(T);

    # if it cannot identify it will just say "data"
    die "Failed to do any identification" unless $raw ne "";

    my @sep = split(/; +/,$raw);
    $mime_type = shift @sep if @sep > 0;
    $mime_encoding = shift @sep if @sep > 0;
}

die "Failed to obtain MIME type" unless $mime_type ne "";

print "$mime_type\n";

