#!/bin/bash
tool=`which convert`
if [ -z "$tool" ]; then echo "This script requires ImageMagick"; fi

file="$1"

# redirect STDIN to file because filenames in my archives *might* have leading dashes.
# quote the filename to prevent cases where quotation marks or angle brackets do unexpected things in the shell.
"$tool" "-""[0]" -resize '640x640>' -quality 20 thumbnail.webp <"$file"
