all:

clean:

install:
	mkdir -p $(DESTDIR)/usr/bin/
	cp -v video-thumbnail $(DESTDIR)/usr/bin/
	cp -v video-preview-video $(DESTDIR)/usr/bin/
	cp -v video-preview-video-audio-only $(DESTDIR)/usr/bin/

