#!/bin/bash
tool=`which ffmpeg`
if [ -z "$tool" ]; then echo "This script requires FFMPEG"; fi

file="$1"
res=320

ffmpeg -i "$file" -acodec libfdk_aac -ab 10000 -profile:a aac_low -ac 1 -ar 8000 -vcodec libx264 -vb 40000 -g 20 -bf 9 -r 4 -vf "yadif=mode=0:parity=auto:deint=interlaced,scale=width='min($res,iw)':height='min($res,ih)':force_original_aspect_ratio=decrease,pad=width='ceil(iw/2)*2':height='ceil(ih/2)*2':x=0:y=0" -crf_max 42 -qmin 34 -qmax 63 -pix_fmt yuv420p -map_metadata -1 -movflags +faststart -y -f mp4 preview.mp4 || exit 1

