#!/bin/bash
tool=`which ffmpeg`
if [ -z "$tool" ]; then echo "This script requires FFMPEG"; fi

file="$1"
res=640

ffmpeg -i "$file" -an -vcodec png -vf "scale='ih*dar':'ih'" -r 1/10 -y thumbnail.%d.png || exit 1

# NTS: Thumbnails at this time are strictly sequentially numbered and do not have
#      any specific timing and mapping. FFMPEG will not generate thumbnails at
#      strictly multiples of 10s i.e. 0s, 10s, 20s. Perhaps a future revision of
#      this system will use a custom program using FFMPEG to generate that, and
#      then timestamps can include the exact timecode in the filename.
i=1
while true; do
    fname="thumbnail.$i.png"
    if [ -f "$fname" ]; then
        image-thumbnail "$fname" || exit 1
        dname=`echo $fname | sed -e 's/png$/webp/'`
        if [ "$dname" == "$fname" ]; then echo doh; exit 1; fi
        mv -v "thumbnail.webp" "$dname" || exit 1
        rm -f "$fname" || exit 1
        i=$(($i+1))
    else
        break
    fi
done

